### ISSUE TITLE
Error executing query

### ISSUE THREAD

**Issue by kittykat** [octokit/graphql-action#110]
One of our actions threw an error earlier today and the error message implied that it should be reported:

`Error: Something went wrong while executing your query. Please include `0781:5AD4:240C07:892C2B:61CC49CB` when reporting this issue.`

![Screenshot from 2021-12-29 12-23-50](https://user-images.githubusercontent.com/51663/147662871-2d1ba10c-11cb-448e-901d-b612bb19571b.png)

The workflow looks like this:
```
    steps:
      - uses: octokit/graphql-action@v2.x
        with:
          headers: '{"GraphQL-Features": "projects_next_graphql"}'
          query: |
            mutation add_to_project($projectid:ID!,$contentid:ID!) {
              addProjectNextItem(input:{projectId:$projectid contentId:$contentid}) {
                projectNextItem {
                  id
                }
              }
            }
          projectid: ${{ env.PROJECT_ID }}
          contentid: ${{ github.event.issue.node_id }}
        env:
          PROJECT_ID: "PN_kwDOAM0swc1HvQ"
          GITHUB_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
```

I re-ran the workflow and it worked on second pass without any issues so urgency to investigate further from our side.

**Comment by wolfy1339** [comment]
That looks like an error that GitHub sent in response to your request.

There isn't much we can do here to help you unfortunately.

If you ever get an error like that again, you should contact GitHub support and they will be able to better assist you
