### ISSUE TITLE
[MAINT]: Bump @actions/core version

### ISSUE THREAD

**Issue by tkorenko** [octokit/graphql-action#201]
### Describe the need

Please consider bumping version of '@actions/core' dependency? Github [recommends](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) using `1.10.0` of `@actions/core`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscard0m** [comment]
Version 1.10.0 of `@actions/core` was landed in October 2022:
- PR: https://github.com/octokit/graphql-action/pull/159
- Git blame: https://github.com/octokit/graphql-action/blame/main/package-lock.json#L24

Dependencies are regularly updated by RenovateBot.
