### ISSUE TITLE
[MAINT]: Update runtime to Node 20

### ISSUE THREAD

**Issue by gr2m** [octokit/graphql-action#239]
### Describe the need

`node20` is now supported as runner (`run.using` in action.yml), as per https://github.com/actions/runner/releases/tag/v2.308.0

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by layonez** [comment]
Is it planned to have a release with that version? I believe latest release v2.2.25 is still using node16

**Comment by gr2m** [comment]
blocked currently by https://github.com/octokit/graphql-action/pull/255
