### ISSUE TITLE
where can I find a pagination example

### ISSUE THREAD

**Issue by markfirmware** [octokit/graphql-action#62]
Looking for an example that retrieves all pages of a query

**Comment by gr2m** [comment]
I fear that is not possible with a single query. But we might be able to add pagination support once we implement the GraphQL pagination plugin for Octokit, see the discussion at https://github.com/octokit/plugin-paginate-graphql.js/pull/1

**Comment by markfirmware** [comment]
> I fear that is not possible with a single query. But we might be able to add pagination support once we implement the GraphQL pagination plugin for Octokit, see the discussion at [octokit/plugin-paginate-graphql.js#1](https://github.com/octokit/plugin-paginate-graphql.js/pull/1)

Thank you for the quick response! I think that I will pull back a little and use js/node or ts/ts-node scripts that are called by an action. You can keep this issue open for tracking, or close it, as you see fit. Thanks again.

**Comment by LlmDl** [comment]
@gr2m Hello,

I'm wondering if pagination support could be added now that the referenced PR has been closed?
