### ISSUE TITLE
How to check workflow runs by this？

### ISSUE THREAD

**Issue by liya2017** [octokit/graphql-action#96]
Hi,
   So glad to see this, may I know how to check workflow runs by this？

**Comment by liya2017** [comment]
below is my job:

```
jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: |
            query release($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                actions(first:1) {
                  nodes {
                    name
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data }}'"
```

and I got error: `Error: Field 'actions' doesn't exist on type 'Repository'`

**Comment by gr2m** [comment]
I recommend you create your query at https://docs.github.com/en/graphql/overview/explorer, that way you will immediately know if a query is valid and if not what is wrong. Could you give that a try?

**Comment by oscard0m** [comment]
Hi @liya2017,

Did you have time to try to reproduce your desired GraphQL query in GitHub's GraphQL Explorer? We would like to know if this issue is relevant.

Thanks

**Comment by liya2017** [comment]
> Hi @liya2017,
> 
> Did you have time to try to reproduce your desired GraphQL query in GitHub's GraphQL Explorer? We would like to know if this issue is relevant.
> 
> Thanks

don't need this anymore, thanks.
